# Generated by Django 3.0 on 2019-12-14 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_number', models.AutoField(primary_key=True, serialize=False)),
                ('overview', models.TextField()),
                ('objective', models.TextField()),
                ('outcome', models.TextField()),
                ('resources', models.TextField()),
                ('test', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('objective', models.TextField()),
                ('outcome', models.TextField()),
                ('resources', models.TextField()),
                ('test', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('outcome', models.TextField()),
                ('objective', models.TextField()),
                ('resources', models.TextField()),
                ('test', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Module')),
            ],
        ),
    ]
