# Generated by Django 3.0 on 2019-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_hours_per_week',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
            preserve_default=False,
        ),
    ]
