# Generated by Django 3.0 on 2019-12-16 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191215_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=50)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Unit'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=50)),
                ('programme_fees', models.IntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=50)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=300)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Level')),
            ],
        ),
    ]
