# Generated by Django 3.0.1 on 2019-12-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_auto_20191226_2258"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Department code",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Department name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AddField(
            model_name="discipline",
            name="offered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.Department",
                verbose_name="Department",
            ),
        ),
    ]
