# Generated by Django 3.0 on 2019-12-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191216_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Unit'),
        ),
    ]
