# Generated by Django 3.0.1 on 2019-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_auto_20191226_2325"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Department short name",
            ),
        ),
    ]
