# Generated by Django 3.0.1 on 2019-12-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_department_department_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionVerb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_verb", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CognitiveLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cognitive_level",
                    models.CharField(max_length=100, unique=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="course", name="course_outcome",),
        migrations.RemoveField(model_name="module", name="module_outcome",),
        migrations.RemoveField(model_name="unit", name="unit_outcome",),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outcome", models.CharField(max_length=255, unique=True)),
                (
                    "action_verb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.ActionVerb",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actionverb",
            name="cognitive_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.CognitiveLevel",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="course_outcome",
            field=models.ManyToManyField(
                blank=True, to="course.Outcome", verbose_name="Course outcome"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="module_outcome",
            field=models.ManyToManyField(
                blank=True, to="course.Outcome", verbose_name="Module outcome"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_outcome",
            field=models.ManyToManyField(
                blank=True, to="course.Outcome", verbose_name="Unit outcome"
            ),
        ),
    ]
