# Generated by Django 3.0.1 on 2019-12-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_auto_20191227_0047"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionverb",
            name="action_verb_short_name",
            field=models.CharField(default="null", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cognitivelevel",
            name="cognitive_level_short_name",
            field=models.CharField(default="null", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="outcome",
            name="outcome_short_name",
            field=models.CharField(default="null", max_length=10),
            preserve_default=False,
        ),
    ]
