# Generated by Django 3.0.1 on 2019-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_auto_20191227_1107"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective", models.CharField(max_length=255, unique=True)),
                (
                    "objective_short_name",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="course", name="course_objective",),
        migrations.RemoveField(model_name="module", name="module_objective",),
        migrations.RemoveField(model_name="unit", name="unit_objective",),
        migrations.AddField(
            model_name="course",
            name="course_objective",
            field=models.ManyToManyField(
                blank=True,
                to="course.Objective",
                verbose_name="Course objective",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="module_objective",
            field=models.ManyToManyField(
                blank=True,
                to="course.Objective",
                verbose_name="Module objective",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_objective",
            field=models.ManyToManyField(
                blank=True, to="course.Objective", verbose_name="Unit objective"
            ),
        ),
    ]
