# Generated by Django 3.0.1 on 2019-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_auto_20191227_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_credit",
            field=models.IntegerField(verbose_name="Course credit"),
        ),
        migrations.AlterField(
            model_name="course",
            name="lecture_contact_hours_per_week",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="practical_contact_hours_per_week",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="tutorial_contact_hours_per_week",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="total_credits",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
