# Generated by Django 3.0.1 on 2019-12-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_auto_20191229_0134"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discipline",
            old_name="offered_by",
            new_name="department",
        ),
    ]
