# Generated by Django 3.0.1 on 2020-01-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_auto_20191230_0145"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcome",
            name="course_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.Course",
            ),
        ),
    ]
