# Generated by Django 3.0.1 on 2020-01-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_auto_20200128_0038"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="outcome", unique_together=set(),),
        migrations.RemoveField(model_name="outcome", name="course_outcome",),
    ]
