# Generated by Django 3.0.1 on 2019-12-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_auto_20191226_1858"),
    ]

    operations = [
        migrations.RemoveField(model_name="discipline", name="offered_by",),
        migrations.AddField(
            model_name="course",
            name="course_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Course short name",
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="discipline_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Discipline short name",
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="institute_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Institute short name",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="level_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Level short name",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="module_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Module short name",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="programme_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Programme short name",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Unit short name",
            ),
        ),
        migrations.DeleteModel(name="Department",),
    ]
