# Generated by Django 3.0.1 on 2019-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_auto_20191227_0057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionverb",
            name="action_verb_short_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cognitivelevel",
            name="cognitive_level_short_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="outcome_short_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
