# Generated by Django 3.0.1 on 2019-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_auto_20191228_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institute",
            name="institute_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Institute name"
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="institute_short_name",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Institute short name",
            ),
        ),
    ]
