# Generated by Django 3.0.1 on 2019-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_auto_20191228_0353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Course title"
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="discipline_name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Discipline name"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="module_title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Module title"
            ),
        ),
    ]
