from OutcomeBasedCourse.config.verbose_names import *


def get_verbose_names(context):
    verbose_names = {
        "INSTITUTE_SINGULAR": INSTITUTE_SINGULAR,
        "INSTITUTE_PLURAL": INSTITUTE_PLURAL,
        "LEVEL_SINGULAR": LEVEL_SINGULAR,
        "LEVEL_PLURAL": LEVEL_PLURAL,
        "PROGRAMME_SINGULAR": PROGRAMME_SINGULAR,
        "PROGRAMME_PLURAL": PROGRAMME_PLURAL,
        "DEPARTMENT_SINGULAR": DEPARTMENT_SINGULAR,
        "DEPARTMENT_PLURAL": DEPARTMENT_PLURAL,
        "DISCIPLINE_SINGULAR": DISCIPLINE_SINGULAR,
        "DISCIPLINE_PLURAL": DISCIPLINE_PLURAL,
        "COURSE_SINGULAR": COURSE_SINGULAR,
        "COURSE_PLURAL": COURSE_PLURAL,
        "MODULE_SINGULAR": MODULE_SINGULAR,
        "MODULE_PLURAL": MODULE_PLURAL,
        "UNIT_SINGULAR": UNIT_SINGULAR,
        "UNIT_PLURAL": UNIT_PLURAL,
    }
    return verbose_names
